# Explicit application resource records. Keep this list non-recursive.
set(MICROTECH_APP_RESOURCE_RECORDS "")
include("${CMAKE_CURRENT_LIST_DIR}/home_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/menu_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/settings_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/setup_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/clock_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/recorder_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/level_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/diagnostics_app/resource_manifest.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/weather_app/resource_manifest.cmake")
