/**
 * @brief Product semantic identities for application-owned images.
 */

#ifndef __APP_IMAGE_IDS_H__
#define __APP_IMAGE_IDS_H__

#define APP_IMAGE_WEATHER_APP                 0x5700U

#define APP_IMAGE_WEATHER_CLEAR_DAY_MAIN      0x5710U
#define APP_IMAGE_WEATHER_CLEAR_NIGHT_MAIN    0x5711U
#define APP_IMAGE_WEATHER_PARTLY_DAY_MAIN     0x5712U
#define APP_IMAGE_WEATHER_PARTLY_NIGHT_MAIN   0x5713U
#define APP_IMAGE_WEATHER_CLOUDY_MAIN         0x5714U
#define APP_IMAGE_WEATHER_OVERCAST_MAIN       0x5715U
#define APP_IMAGE_WEATHER_DRIZZLE_MAIN        0x5716U
#define APP_IMAGE_WEATHER_RAIN_MAIN           0x5717U
#define APP_IMAGE_WEATHER_HEAVY_RAIN_MAIN     0x5718U
#define APP_IMAGE_WEATHER_THUNDER_MAIN        0x5719U
#define APP_IMAGE_WEATHER_HAIL_MAIN           0x571AU
#define APP_IMAGE_WEATHER_FREEZING_RAIN_MAIN  0x571BU
#define APP_IMAGE_WEATHER_SNOW_MAIN           0x571CU
#define APP_IMAGE_WEATHER_HEAVY_SNOW_MAIN     0x571DU
#define APP_IMAGE_WEATHER_SLEET_MAIN          0x571EU
#define APP_IMAGE_WEATHER_FOG_MAIN            0x571FU
#define APP_IMAGE_WEATHER_HAZE_MAIN           0x5720U
#define APP_IMAGE_WEATHER_HOT_MAIN            0x5721U
#define APP_IMAGE_WEATHER_COLD_MAIN           0x5722U
#define APP_IMAGE_WEATHER_UNKNOWN_MAIN        0x5723U

#define APP_IMAGE_WEATHER_CLEAR_DAY_SMALL     0x5740U
#define APP_IMAGE_WEATHER_CLEAR_NIGHT_SMALL   0x5741U
#define APP_IMAGE_WEATHER_PARTLY_DAY_SMALL    0x5742U
#define APP_IMAGE_WEATHER_PARTLY_NIGHT_SMALL  0x5743U
#define APP_IMAGE_WEATHER_CLOUDY_SMALL        0x5744U
#define APP_IMAGE_WEATHER_OVERCAST_SMALL      0x5745U
#define APP_IMAGE_WEATHER_DRIZZLE_SMALL       0x5746U
#define APP_IMAGE_WEATHER_RAIN_SMALL          0x5747U
#define APP_IMAGE_WEATHER_HEAVY_RAIN_SMALL    0x5748U
#define APP_IMAGE_WEATHER_THUNDER_SMALL       0x5749U
#define APP_IMAGE_WEATHER_HAIL_SMALL          0x574AU
#define APP_IMAGE_WEATHER_FREEZING_RAIN_SMALL 0x574BU
#define APP_IMAGE_WEATHER_SNOW_SMALL           0x574CU
#define APP_IMAGE_WEATHER_HEAVY_SNOW_SMALL    0x574DU
#define APP_IMAGE_WEATHER_SLEET_SMALL         0x574EU
#define APP_IMAGE_WEATHER_FOG_SMALL           0x574FU
#define APP_IMAGE_WEATHER_HAZE_SMALL          0x5750U
#define APP_IMAGE_WEATHER_HOT_SMALL           0x5751U
#define APP_IMAGE_WEATHER_COLD_SMALL          0x5752U
#define APP_IMAGE_WEATHER_UNKNOWN_SMALL       0x5753U

#define APP_IMAGE_HOME_ICON                   0x5760U
#define APP_IMAGE_MENU_ICON                   0x5761U
#define APP_IMAGE_SETTINGS_ICON               0x5762U
#define APP_IMAGE_SETUP_ICON                  0x5763U
#define APP_IMAGE_CLOCK_ICON                  0x5764U
#define APP_IMAGE_RECORDER_ICON               0x5765U
#define APP_IMAGE_LEVEL_ICON                  0x5766U
#define APP_IMAGE_DIAGNOSTICS_ICON            0x5767U

#endif /* __APP_IMAGE_IDS_H__ */
