# 天气状况图标源为 QWeather Icons（MIT，icons/N-fill.svg 变体，vendor 时已将
# currentColor 替换为主题色，见 assets/qweather-icons-LICENSE.txt 与
# layers/apps/README.md 资源小节）。同一 SVG 登记 40/112 两条尺寸记录；
# weather_app.svg 为自绘 App 图标，与 QWeather 无关。
list(APPEND MICROTECH_APP_RESOURCE_RECORDS
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_app.svg|weather_app.png|APP_IMAGE_WEATHER_APP|64|64|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_clear_day.svg|weather_clear_day_112.png|APP_IMAGE_WEATHER_CLEAR_DAY_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_clear_day.svg|weather_clear_day_40.png|APP_IMAGE_WEATHER_CLEAR_DAY_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_clear_night.svg|weather_clear_night_112.png|APP_IMAGE_WEATHER_CLEAR_NIGHT_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_clear_night.svg|weather_clear_night_40.png|APP_IMAGE_WEATHER_CLEAR_NIGHT_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_partly_day.svg|weather_partly_day_112.png|APP_IMAGE_WEATHER_PARTLY_DAY_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_partly_day.svg|weather_partly_day_40.png|APP_IMAGE_WEATHER_PARTLY_DAY_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_partly_night.svg|weather_partly_night_112.png|APP_IMAGE_WEATHER_PARTLY_NIGHT_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_partly_night.svg|weather_partly_night_40.png|APP_IMAGE_WEATHER_PARTLY_NIGHT_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_cloudy.svg|weather_cloudy_112.png|APP_IMAGE_WEATHER_CLOUDY_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_cloudy.svg|weather_cloudy_40.png|APP_IMAGE_WEATHER_CLOUDY_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_overcast.svg|weather_overcast_112.png|APP_IMAGE_WEATHER_OVERCAST_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_overcast.svg|weather_overcast_40.png|APP_IMAGE_WEATHER_OVERCAST_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_drizzle.svg|weather_drizzle_112.png|APP_IMAGE_WEATHER_DRIZZLE_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_drizzle.svg|weather_drizzle_40.png|APP_IMAGE_WEATHER_DRIZZLE_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_rain.svg|weather_rain_112.png|APP_IMAGE_WEATHER_RAIN_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_rain.svg|weather_rain_40.png|APP_IMAGE_WEATHER_RAIN_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_heavy_rain.svg|weather_heavy_rain_112.png|APP_IMAGE_WEATHER_HEAVY_RAIN_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_heavy_rain.svg|weather_heavy_rain_40.png|APP_IMAGE_WEATHER_HEAVY_RAIN_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_thunder.svg|weather_thunder_112.png|APP_IMAGE_WEATHER_THUNDER_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_thunder.svg|weather_thunder_40.png|APP_IMAGE_WEATHER_THUNDER_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_hail.svg|weather_hail_112.png|APP_IMAGE_WEATHER_HAIL_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_hail.svg|weather_hail_40.png|APP_IMAGE_WEATHER_HAIL_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_freezing_rain.svg|weather_freezing_rain_112.png|APP_IMAGE_WEATHER_FREEZING_RAIN_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_freezing_rain.svg|weather_freezing_rain_40.png|APP_IMAGE_WEATHER_FREEZING_RAIN_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_snow.svg|weather_snow_112.png|APP_IMAGE_WEATHER_SNOW_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_snow.svg|weather_snow_40.png|APP_IMAGE_WEATHER_SNOW_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_heavy_snow.svg|weather_heavy_snow_112.png|APP_IMAGE_WEATHER_HEAVY_SNOW_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_heavy_snow.svg|weather_heavy_snow_40.png|APP_IMAGE_WEATHER_HEAVY_SNOW_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_sleet.svg|weather_sleet_112.png|APP_IMAGE_WEATHER_SLEET_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_sleet.svg|weather_sleet_40.png|APP_IMAGE_WEATHER_SLEET_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_fog.svg|weather_fog_112.png|APP_IMAGE_WEATHER_FOG_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_fog.svg|weather_fog_40.png|APP_IMAGE_WEATHER_FOG_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_haze.svg|weather_haze_112.png|APP_IMAGE_WEATHER_HAZE_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_haze.svg|weather_haze_40.png|APP_IMAGE_WEATHER_HAZE_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_hot.svg|weather_hot_112.png|APP_IMAGE_WEATHER_HOT_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_hot.svg|weather_hot_40.png|APP_IMAGE_WEATHER_HOT_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_cold.svg|weather_cold_112.png|APP_IMAGE_WEATHER_COLD_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_cold.svg|weather_cold_40.png|APP_IMAGE_WEATHER_COLD_SMALL|40|40|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_unknown.svg|weather_unknown_112.png|APP_IMAGE_WEATHER_UNKNOWN_MAIN|112|112|SVG"
    "${CMAKE_CURRENT_LIST_DIR}/assets/weather_unknown.svg|weather_unknown_40.png|APP_IMAGE_WEATHER_UNKNOWN_SMALL|40|40|SVG")
